psr_type = {
    'B01':'Biomassa',
    'B02':'Lignite',
    'B03':'Gas derivato',
    'B04':'Gas naturale',
    'B05':'Carbone',
    'B09':'Geotermico',
    'B10':'Idroelettrico pompaggio',
    'B11':'Idroelettrico fluente',
    'B12':'Idroelettrico bacino',
    'B14':'Nucleare',
    'B16':'Solare',
    'B17':'Rifiuti',
    'B18':'Eolico offshore',
    'B19':'Eolico onshore',
    'B20':'Altro'
}

type_translation = {
    'Biomass':'Biomassa',
    'Fossil Brown coal/Lignite':'Lignite',
    'Fossil Coal-derived gas':'Gas derivato',
    'Fossil Gas':'Gas naturale',
    'Fossil Hard coal':'Carbone',
    'Geothermal':'Geotermico',
    'Hydro Pumped Storage':'Idroelettrico pompaggio',
    'Hydro Run-of-river and poundage':'Idroelettrico fluente',
    'Hydro Water Reservoir':'Idroelettrico bacino',
    'Nuclear':'Nucleare',
    'Solar':'Solare',
    'Waste':'Rifiuti',
    'Wind Offshore':'Eolico offshore',
    'Wind Onshore':'Eolico onshore',
    'Other':'Altro'
}

country_code = {
    'Norvegia':'NO',
    'Svezia':'SE', 
    'Finlandia':'FI',
    'Estonia':'EE', 
    'Lettonia':'LV',
    'Lituania':'LT',
    'Polonia':'PL',
    'Germania':'DE',
    'Danimarca':'DK',
    'Paesi Bassi':'NL',
    'Belgio':'BE',
    'Francia':'FR',
    'Spagna':'ES',
    'Portogallo':'PT',
    'Svizzera':'CH',
    'Austria':'AT',
    'Repubblica Ceca':'CZ',
    'Slovacchia':'SK',
    'Ungheria':'HU',
    'Slovenia':'SI',
    'Croazia':'HR',
    'Bosnia - Erzegovina':'BA',
    'Grecia':'GR',
    'Georgia':'GE',
    'Macedonia':'MK',
    'Kosovo':'KX',
    'Serbia':'RS',
    'Romania':'RO',
    'Bulgaria':'BG',
    'Montenegro':'ME',
    'Italia':'IT',
    'Irlanda':'IE',
    'Albania':'AL'
}

country_translation = {
    "Albania": "Albania",
    "Austria": "Austria",
    "Belgium": "Belgio",
    "Bulgaria": "Bulgaria",
    "Croatia": "Croazia",
    "Cyprus": "Cipro",
    "Czechia": "Cechia",
    "Denmark": "Danimarca",
    "Estonia": "Estonia",
    "Finland": "Finlandia",
    "France": "Francia",
    "Germany": "Germania",
    "Greece": "Grecia",
    "Hungary": "Ungheria",
    "Iceland": "Islanda",
    "Ireland": "Irlanda",
    "Italy": "Italia",
    "Kosovo*": "Kosovo*",
    "Latvia": "Lettonia",
    "Lithuania": "Lituania",
    "Luxembourg": "Lussemburgo",
    "Malta": "Malta",
    "Moldova": "Moldavia",
    "Montenegro": "Montenegro",
    "Netherlands": "Paesi Bassi",
    "North Macedonia": "Macedonia del Nord",
    "Norway": "Norvegia",
    "Poland": "Polonia",
    "Portugal": "Portogallo",
    "Romania": "Romania",
    "Serbia": "Serbia",
    "Slovakia": "Slovacchia",
    "Slovenia": "Slovenia",
    "Spain": "Spagna",
    "Sweden": "Svezia",
    "Türkiye": "Turchia"
}
